### ISSUE TITLE
member counter is in unusual positions

### ISSUE THREAD

**Issue by speedlorenzo12** [SyndiShanX/Better-Discord-Plugins#10]
(this message may change as I may find more unusual locations)
votation area
![Screenshot 2024-06-07 160934](https://github.com/SyndiShanX/Better-Discord-Plugins/assets/111771663/9f443d8d-f30b-4c33-a41d-e2a788c0e809)

**Comment by SyndiShanX** [comment]
Where is that?

**Comment by speedlorenzo12** [comment]
When you look at which people voted for an option

**Comment by SyndiShanX** [comment]
Should be fixed once the update is approved
