### ISSUE TITLE
[Feature Request] Show all status groupings

### ISSUE THREAD

**Issue by zerebos** [SyndiShanX/Better-Discord-Plugins#4]
Currently the plugin only shows offline vs offline. Is it possible to show counts of idle, streaming, and DND? Would also be nice to have all of them (including online) toggle-able or even rearrange-able.

**Comment by zrodevkaan** [comment]
From what I am seeing, I do not think this is possible. We have no way of getting all users without permissions and discord doesn't hand us all user information as easily as we hoped. All the information we get is roles, highest role, nick, etc...

Really wouldn't be a "MemberCounter" if you had to scroll to get barely any information. 

I guess looping through the MemberList and getting the react components then finding the status of each user would work but at the end of the day still wouldn't work as accurately.
