### ISSUE TITLE
Member Counter (BUG)

### ISSUE THREAD

**Issue by deadmau1** [SyndiShanX/Better-Discord-Plugins#5]
Plugin not showing Online/Offline Members

![image](https://github.com/SyndiShanX/Better-Discord-Plugins/assets/115784191/7f3c219d-21be-4b8e-b04f-e1929911eaab)

![image](https://github.com/SyndiShanX/Better-Discord-Plugins/assets/115784191/4a83e142-c798-4bb0-adbe-ac05806e4184)

**Comment by SyndiShanX** [comment]
That means that you're in a thread which doesn't have a great way to fetch the offline members, plus you can usually see the offline members if you scroll down the members list a bit since there usually aren't that many members

**Comment by SyndiShanX** [comment]
Nvm, discord is returning unknown values for some reason

**Comment by SyndiShanX** [comment]
Should be fixed, thanks for Reporting
