### ISSUE TITLE
[Feature Request] Thread Member Counts

### ISSUE THREAD

**Issue by Huderon** [SyndiShanX/Better-Discord-Plugins#6]
Currently when in a thread it the counters cap at 50. You should be able to do this properly now using something like this 

`BdApi.Webpack.getStore("ThreadMemberListStore").getMemberListSections(BdApi.Webpack.getStore("SelectedChannelStore").getCurrentlySelectedChannelId())`

**Comment by Huderon** [comment]
What? It'd work exactly the same as your current method for summing online count for regular channels

**Comment by SyndiShanX** [comment]
It took quite a bit of Tinkering, but I got it working, thank you
