### ISSUE TITLE
MemberCounter bug all three counters are on the same spot on top of the members list

### ISSUE THREAD

**Issue by jack652** [SyndiShanX/Better-Discord-Plugins#7]
MemberCounter bug all three counters are on the same spot on top of the members list

![image](https://github.com/SyndiShanX/Better-Discord-Plugins/assets/48365199/ae8b8b8e-4854-4ec5-868a-fae00be6b3e3)

**Comment by SyndiShanX** [comment]
I fixed this last night, just waiting on Better Discord to approve the update
